apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-common-config
  namespace: blog-system
data:
  nacos-ip: "veweiyi.cn"
  nacos-port: "8848"
  nacos-namespace: "prod"
  nacos-group: "veweiyi.cn"
---
apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
  namespace: blog-system
type: Opaque
data:
  nacos-username: bmFjb3M=          # echo -n "nacos" | base64
  nacos-password: bmFjb3M=          # echo -n "nacos" | base64